name: Test (Reusable)

on:
  workflow_call:
    inputs:
      scale_up:
        description: up
        required: true
        type: boolean
      scale_down:
        description: up
        required: true
        type: boolean

jobs:
  change-sql-dtu:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: down
      if: {{ inputs.scale_down }}
      shell: bash
      run: |
        echo "down" 
    
    - name: up
      if: {{ inputs.scale_up }}
      shell: bash
      run: |
        echo "up" 


