name: my Name

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '30 12 * * 1-5'  # 30: minute, 12: hour, any day of month, any month, 1-5 Monday to Friday
  #  - cron: '15 18 * * 1-5'

env:
  upscale_cron:   '30 4 * * 1-5'
  downscale_cron: '15 18 * * 1-5'

jobs:
  change-sql-dtu:
    uses: ./.github/workflows/test-reusable.yml
    with:
      scale_down: ${{ github.event.schedule == env.downscale_cron }}
      scale_up:   ${{ github.event.schedule == env.upscale_cron }}
