name: my Name

on:
  workflow_dispatch:
  schedule:
    - cron: '30 12 * * 1-5'  # 30: minute, 12: hour, any day of month, any month, 1-5 Monday to Friday
    - cron: '40 16 * * 1-5' 

jobs:
  change-sql-dtu:
    uses: ./.github/workflows/test-reusable.yml
    if: github.event.schedule == '40 16 * * 1-5'
